// packages/kobber-components-poc/src/components/card/svelte/card-text-title.svelte
<script lang="ts">
    import * as css from "../css/card-text-title.module.css";
    import { getCardContext } from "./card-context";

    let props = $props();
    let { children } = props;
    const { api } = getCardContext();
    const classes = `${css.cardTextTitle} ${api && api().active ? css.active : css.inactive}`;
</script>

<div class={classes} {...props}>
    {@render children?.()}
</div>

// packages/kobber-components-poc/src/components/card/react/card-text-title.tsx
import * as css from "../css/card-text-title.module.css";
import { useCardContext } from "./card-context";

export const CardTextTitle: React.FC<any> = ({ children, ...props }) => {
  const { api } = useCardContext();
  const classes = `${css.cardTextTitle} ${
    api && api().active ? css.active : css.inactive
  }`;

  return (
    <div className={classes} {...props}>
      {children}
    </div>
  );
};
