// packages/kobber-components-poc/src/components/card/svelte/card-media-layer.svelte
<script lang="ts">
import { cardMediaLayerApi } from "../index.api";
import { getCardContext } from "./card-context";

const props = $props();
const { base, children } = props;
const { direction } = getCardContext();
const css = cardMediaLayerApi({ direction, base });
const classes = `${css.root.className} ${props.class}`;
</script>

<div class={classes} {...props}>
    {@render children?.()}
</div>

// packages/kobber-components-poc/src/components/card/react/card-media-layer.tsx
import { cardMediaLayerApi } from "../index.api";
import { useCardContext } from "./card-context";

interface CardMediaLayerProps extends React.HTMLAttributes<HTMLDivElement> {
  base?: boolean;
}

export const CardMediaLayer: React.FC<CardMediaLayerProps> = ({
  base = false,
  children,
  className,
  ...props
}) => {
  const { direction } = useCardContext();
  const css = cardMediaLayerApi({ direction, base });
  const classes = `${css.root.className} ${className}`;
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  );
};
