// packages/kobber-components-poc/src/components/card/svelte/card.svelte
<script lang="ts">
    import { machine, connect, type CardMachineSchema } from "@gyldendal/kobber-components-core/card/card.core.js";
    import { normalizeProps, useMachine } from "@zag-js/svelte";
    import { getCardContext, setCardContext } from "./card-context";
    import * as css from "../css/card.css";
    import type { HTMLAttributes } from 'svelte/elements'

    interface CardProps extends HTMLAttributes<HTMLDivElement> {
      direction?: "vertical" | "horizontal";
      element?: string;
      disabled?: boolean;
    }
    let props = $props();
    let { direction = "vertical", disabled = false, children } = props as CardProps;
    const service = useMachine<CardMachineSchema>(machine, { disabled: disabled });
    const api = $derived(connect(service, normalizeProps));
    const apiRef = () => api;
    setCardContext({api: apiRef, link: null, registerLink: () => {}, direction});
    const context = getCardContext();

    const classes = `${css.card} ${direction ? css[direction] : ""}`
</script>

<div class={classes}  {...context.api().getCardProps()}>
    {@render children?.()}
</div>

// packages/kobber-components-poc/src/components/card/react/card.tsx
import { normalizeProps, useMachine } from "@zag-js/react";
import type React from "react";
import { useState } from "react";
import { cardApi } from "../index.api";
import {
  type CardMachineSchema,
  type CardProps,
  connect,
  machine,
} from "../state/card.core.js";
import { ReactCardContext } from "./card-context";

interface CardReactProps
  extends CardProps,
    React.HTMLAttributes<HTMLDivElement> {}

export const Card: React.FC<CardReactProps> = ({
  direction = "vertical",
  disabled = false,
  children,
  className = "",
  ...props
}) => {
  const api = connect(
    useMachine<CardMachineSchema>(machine, { disabled: disabled }),
    normalizeProps
  );
  const [link, setLink] = useState<HTMLAnchorElement | null>(null);
  const css = cardApi({ direction });
  const classes = `${css.root.className} ${className ? className : ""}`;
  return (
    <ReactCardContext.Provider
      value={{
        api: () => api,
        registerLink: setLink,
        link: link,
        direction: direction,
      }}
    >
      <div {...api.getCardProps()} className={classes} {...props}>
        {children}
      </div>
    </ReactCardContext.Provider>
  );
};
