// packages/kobber-components-poc/src/components/card/svelte/card-text-wrapper.svelte
<script lang="ts">
  import * as css from "../css/card-text-wrapper.css";
  import { getCardContext } from "./card-context";
  let props = $props();
  let { children } = props;
  const { direction } = getCardContext();

  const classes = `${css.cardTextWrapper} ${
      direction === "horizontal" ? css.horizontal : ""
  }`;

</script>

<div class={classes} {...props}>
    {@render children?.()}
</div>

// packages/kobber-components-poc/src/components/card/react/card-text-wrapper.tsx
import * as css from "../css/card-text-wrapper.css";
import { useCardContext } from "./card-context";

export const CardTextWrapper: React.FC<any> = ({ children, ...props }) => {
  const { direction } = useCardContext();
  const classes = `${css.cardTextWrapper} ${
    direction === "horizontal" ? css.horizontal : ""
  }`;

  return (
    <div className={classes} {...props}>
      {children}
    </div>
  );
};
