// packages/kobber-components-poc/src/components/svelte/select/Select.svelte
<script lang="ts">
import type { SelectOptions } from "@gyldendal/kobber-components-core/select/select";
import * as select from "@zag-js/select";
import { normalizeProps, portal } from "@zag-js/svelte";
import { svelteSelect } from "./useSelect.svelte";

const props: SelectOptions = $props();

const { service } = svelteSelect({ ...props });
const api = $derived(select.connect(service, normalizeProps));
</script>

<div {...api.getRootProps()}>
  <div {...api.getControlProps()}>
    <label {...api.getLabelProps()}>Label</label>
    <button {...api.getTriggerProps()}>
      {api.valueAsString || "Svelte Select"}
    </button>
  </div>

  <div use:portal {...api.getPositionerProps()}>
    <ul {...api.getContentProps()}>
      {#each props.items as item}
        <li {...api.getItemProps({ item })}>
          <span {...api.getItemTextProps({ item })}>{item.label}</span>
          <span {...api.getItemIndicatorProps({ item })}>✓</span>
        </li>
      {/each}
    </ul>
  </div>
</div>

// packages/kobber-components-poc/src/components/react/select/Select.tsx
import type { SelectOptions } from "@gyldendal/kobber-components-core/select/select";
import { Portal } from "@zag-js/react";
import { useSelect } from "./useSelect";

export function Select(props: SelectOptions) {
  const api = useSelect({ ...props });
  return (
    <div {...api.getRootProps()}>
      <div {...api.getControlProps()}>
        {/** biome-ignore lint/a11y/noLabelWithoutControl: "" */}
        <label {...api.getLabelProps()}>Label</label>
        <button {...api.getTriggerProps()}>
          {api.valueAsString || "React Select"}
        </button>
      </div>
      <Portal>
        <div {...api.getPositionerProps()}>
          <ul {...api.getContentProps()}>
            {props.items.map((item) => (
              <li key={item.value} {...api.getItemProps({ item })}>
                <span>{item.label}</span>
                <span {...api.getItemIndicatorProps({ item })}>✓</span>
              </li>
            ))}
          </ul>
        </div>
      </Portal>
    </div>
  );
}
