// packages/kobber-components-poc/src/components/toggleButton/root/ToggleButton.react.tsx
import * as toggleButton from "@gyldendal/kobber-components-core/toggleButton/toggleButton";
import { normalizeProps, useMachine } from "@zag-js/react";
import type { ReactNode } from "react";
import { getClassNames } from "./core";

interface Props {
  state: toggleButton.State;
  children?: ReactNode;
}

export const ToggleButton = ({ children, ...props }: Props) => {
  const service = useMachine(toggleButton.machine, props);
  const api = toggleButton.connect(service, normalizeProps);
  const classNames = getClassNames(api);
  return (
    <button {...api.getButtonProps()} className={classNames.root}>
      {children}
    </button>
  );
};

// packages/kobber-components-poc/src/components/toggleButton/root/ToggleButton.svelte
<script lang="ts">
import * as toggleButton from "@gyldendal/kobber-components-core/toggleButton/toggleButton";
import { normalizeProps, useMachine } from "@zag-js/svelte";
import type { Snippet } from "svelte";
import { getClassNames } from "./core";

const props: { state: toggleButton.State; children: Snippet } = $props();

// biome-ignore lint/correctness/useHookAtTopLevel: ""
const service = useMachine(toggleButton.machine, props);
const api = $derived(toggleButton.connect(service, normalizeProps));
const classNames = $derived(getClassNames(api));
</script>

<button
  {...api.getButtonProps()}
  class={classNames.root}
>
  {@render props.children()}
</button>
