// packages/kobber-components-poc/src/components/card/react/card-media.tsx
import { cardMediaApi } from "../index.api";
import type { CardMediaType } from "../state/card.core.js";
import { useCardContext } from "./card-context";

export interface CardMediaProps extends React.HTMLAttributes<HTMLDivElement> {
  mediaType?: CardMediaType;
}

export const CardMedia: React.FC<CardMediaProps> = ({
  mediaType = "img",
  children,
  className,
  ...props
}) => {
  const { direction } = useCardContext();
  const css = cardMediaApi({ direction, mediaType });

  const classes = `${css.root.className}  ${className}`;

  return (
    <div className={classes} {...props}>
      {children}
    </div>
  );
};

// packages/kobber-components-poc/src/components/card/svelte/card-media.svelte
<script lang="ts">
    import { cardMediaApi } from "../index.api";
    import { getCardContext } from "./card-context";

    let props = $props();
    let { mediaType = "img", children } = props;
    const { direction } = getCardContext();
    const css = cardMediaApi({direction, mediaType});
    const classes = `${css.root.className} ${props.class}`;
</script>

<div class={classes} {...props}>
    {@render children?.()}
</div>
