// packages/kobber-components-poc/src/components/card/react/card-media-wrapper.tsx
import { cardMediaWrapperApi } from "../index.api";
import { useCardContext } from "./card-context";

export const CardMediaWrapper: React.FC<any> = ({
  children,
  className,
  ...props
}) => {
  const { direction } = useCardContext();
  const css = cardMediaWrapperApi({ direction });
  const classes = `${css.root.className} ${className}`;
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  );
};

// packages/kobber-components-poc/src/components/card/svelte/card-media-wrapper.svelte
<script lang="ts">
    import { cardMediaWrapperApi } from "../index.api";
    import { getCardContext } from "./card-context";

    let props = $props();
    let { children } = props;
    const { direction } = getCardContext();
    const css = cardMediaWrapperApi({direction});
    const classes = `${css.root.className} ${props.class}`;
</script>

<div class={classes} {...props}>
    {@render children?.()}
</div>
